# Welcome to Jekyll!

# # Build settings
# markdown: kramdown
auto: true # automatically update your jekyll
server: true # runs a local server
paginate: 10 # pagination basted on number of posts
exclude: ["README.md", 'sass', 'style.scss'] # files to exclude
